version: '3.8' # Updated to the latest version for better support

services:
  jupyter:
    build:
      context: ./docker
      dockerfile: Dockerfile.jupyter
    container_name: jupyter
    ports:
      - '8888:8888'
    volumes:
      - './notebook:/home/jovyan/work'
    networks:
      - mlflow
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=mlflow
      - AWS_ACCESS_KEY_ID=mlflow
      - AWS_SECRET_ACCESS_KEY=password
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - minio

  mlflow-web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: mlflow-mlflow-web-1
    ports:
      - '5000:5000'
    environment:
      - AWS_ACCESS_KEY_ID=mlflow
      - AWS_SECRET_ACCESS_KEY=password
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - BACKEND_STORE_URI=postgresql+psycopg2://mlflow:secret@pgsql/mlflow
      - ARTIFACT_ROOT=s3://mlflow/
    networks:
      - mlflow
    command: >
      mlflow server 
      --backend-store-uri $BACKEND_STORE_URI
      --default-artifact-root $ARTIFACT_ROOT 
      --host 0.0.0.0
    depends_on:
      - pgsql
      - minio

  minio:
    image: 'minio/minio:latest'
    container_name: mlflow-minio-1
    ports:
      - '9000:9000'
      - '8900:8900'
    environment:
      MINIO_ROOT_USER: mlflow
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'mlflow-minio:/data/minio'
    networks:
      - mlflow
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s

  pgsql:
    image: 'postgres:14'
    container_name: mlflow-pgsql-1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: secret
    volumes:
      - 'mlflow-pgsql:/var/lib/postgresql/data'
    networks:
      - mlflow
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - mlflow
        - '-U'
        - mlflow
      retries: 3
      timeout: 5s

networks:
  mlflow:
    driver: bridge

volumes:
  mlflow-pgsql:
    driver: local
  mlflow-minio:
    driver: local
